# An example credentials file for selector4nix.
# For a complete reference of all available fields, see docs/credentials.md.

[[credentials]]
# URL prefix to match against upstream substituter request URLs.
url = "https://public.example.org/"
# Username or access key for authentication.
login = "user"

[[credentials]]
url = "https://my-server.example.org/nix/private/"
login = "user"
# Password or secret token for authentication, omit when the upstream only requires a login (default: none).
secret = "pass"
