# A development-oriented configuration of selector4nix.
# The configuration key-value pairs listed here are not exhaustive and not supposed to be used as an
# example. For a complete reference of all available fields, see docs/configuration.md.

[server]
ip = "127.0.0.1"
port = 5497

[[substituters]]
url = "https://cache.nixos.org/"
priority = 40

[[substituters]]
url = "https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store/"
priority = 45
nar_info_timeout_secs = 30
nar_timeout_secs = 30

[[substituters]]
url = "https://mirrors.ustc.edu.cn/nix-channels/store/"
priority = 45

[[substituters]]
url = "https://mirror.sjtu.edu.cn/nix-channels/store/"
priority = 45

[[substituters]]
url = "https://nix-community.cachix.org/"
priority = 40

[[substituters]]
url = "https://cache.garnix.io/"
storage_url = "https://garnix-cache.com/"
priority = 40
